import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    // <div className="name-page">
    //   <h1>タスク</h1>
    //
    //   <Link href={"/edit/todo"}>Todoリストを編集する</Link>
    // </div>
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Ponyo!!</h1>
        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>
            {" "}
            <Link href={"/edit/todo"}>Todoリストを編集する</Link>
          </code>
        </p>
      </main>
    </div>
  );
};

export default Home;
